<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SoalTeori;
use App\Models\Skema;
use App\Models\User;

class SoalTeoriSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('role', 'admin')->first();
        $dibuatOleh = $admin?->id ?? 1;

        $skemas = Skema::where('is_active', true)->get();

        if ($skemas->isEmpty()) {
            $this->command->warn('Tidak ada skema aktif. Jalankan DatabaseSeeder terlebih dahulu.');
            return;
        }

        foreach ($skemas as $skema) {
            $soalList = $this->getSoalForSkema($skema->name, $skema->code);

            $inserted = 0;
            foreach ($soalList as $soal) {
                SoalTeori::firstOrCreate(
                    [
                        'skema_id'   => $skema->id,
                        'pertanyaan' => $soal['pertanyaan'],
                    ],
                    [
                        'pilihan_a'     => $soal['a'],
                        'pilihan_b'     => $soal['b'],
                        'pilihan_c'     => $soal['c'],
                        'pilihan_d'     => $soal['d'],
                        'pilihan_e'     => $soal['e'] ?? null,
                        'jawaban_benar' => $soal['jawaban'],
                        'dibuat_oleh'   => $dibuatOleh,
                    ]
                );
                $inserted++;
            }

            $this->command->info("✅ Skema [{$skema->code}] {$skema->name}: {$inserted} soal dimasukkan.");
        }

        $this->command->newLine();
        $this->command->info('Selesai! Total skema: ' . $skemas->count());
    }

    // =========================================================================
    // Soal per skema — 90 soal per skema (cukup untuk distribusi 30 random)
    // Topik: administrasi perkantoran, kesekretariatan, manajemen kantor
    // =========================================================================

    private function getSoalForSkema(string $namaSkema, string $kode): array
    {
        // Semua skema mendapat soal yang sama (basis administrasi perkantoran)
        // dengan sedikit variasi konteks sesuai nama skema
        return $this->soalAdministrasiPerkantoran();
    }

    private function soalAdministrasiPerkantoran(): array
    {
        return [
            // ── KOMUNIKASI & KORESPONDENSI (1-15) ──────────────────────────
            [
                'pertanyaan' => 'Surat resmi yang dibuat oleh instansi pemerintah atau swasta untuk keperluan dinas disebut...',
                'a' => 'Surat pribadi',
                'b' => 'Surat dinas',
                'c' => 'Surat niaga',
                'd' => 'Surat pemberitahuan',
                'e' => 'Surat edaran',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Bagian surat yang berisi inti pokok permasalahan yang disampaikan disebut...',
                'a' => 'Kepala surat',
                'b' => 'Pembuka surat',
                'c' => 'Isi surat',
                'd' => 'Penutup surat',
                'e' => 'Tembusan',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Dalam penulisan surat bisnis, singkatan "u.p." berarti...',
                'a' => 'Untuk perhatian',
                'b' => 'Untuk pengecekan',
                'c' => 'Untuk pertimbangan',
                'd' => 'Untuk peninjauan',
                'e' => 'Atas perhatian',
                'jawaban' => 'a',
            ],
            [
                'pertanyaan' => 'Komunikasi yang dilakukan secara langsung (tatap muka) antara pengirim dan penerima pesan disebut komunikasi...',
                'a' => 'Tidak langsung',
                'b' => 'Verbal',
                'c' => 'Langsung',
                'd' => 'Nonverbal',
                'e' => 'Tertulis',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Berikut ini yang BUKAN merupakan fungsi surat adalah...',
                'a' => 'Sebagai alat komunikasi',
                'b' => 'Sebagai bukti tertulis',
                'c' => 'Sebagai alat pengingat',
                'd' => 'Sebagai hiburan',
                'e' => 'Sebagai duta organisasi',
                'jawaban' => 'd',
            ],
            [
                'pertanyaan' => 'Notula rapat (minutes of meeting) yang baik harus mencakup hal-hal berikut, KECUALI...',
                'a' => 'Hari, tanggal, dan tempat rapat',
                'b' => 'Daftar hadir peserta rapat',
                'c' => 'Agenda dan hasil keputusan rapat',
                'd' => 'Opini pribadi notulen tentang peserta',
                'e' => 'Tanda tangan pimpinan rapat',
                'jawaban' => 'd',
            ],
            [
                'pertanyaan' => 'Jenis surat yang digunakan untuk memesan barang kepada supplier disebut...',
                'a' => 'Surat penawaran',
                'b' => 'Surat pesanan',
                'c' => 'Surat konfirmasi',
                'd' => 'Surat tagihan',
                'e' => 'Surat perjanjian',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Bahasa yang digunakan dalam surat resmi/dinas harus bersifat...',
                'a' => 'Informal dan santai',
                'b' => 'Berbunga-bunga dan panjang',
                'c' => 'Formal, jelas, dan efektif',
                'd' => 'Singkat meski tidak lengkap',
                'e' => 'Teknis dan berbelit',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Dalam teknik menelepon yang efektif, hal pertama yang harus dilakukan saat menerima telepon adalah...',
                'a' => 'Menanyakan keperluan penelepon',
                'b' => 'Mengangkat telepon dan menyebutkan identitas',
                'c' => 'Meminta penelepon menunggu',
                'd' => 'Mencatat pesan terlebih dahulu',
                'e' => 'Menghubungi atasan',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'E-mail bisnis yang profesional sebaiknya menggunakan...',
                'a' => 'Alamat email pribadi dengan nama panggilan',
                'b' => 'Alamat email perusahaan dengan nama lengkap',
                'c' => 'Semua huruf kapital agar terlihat tegas',
                'd' => 'Emoji untuk memperjelas emosi',
                'e' => 'CC ke semua kontak agar lebih diketahui',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Apa yang dimaksud dengan "blind carbon copy" (BCC) dalam pengiriman email?',
                'a' => 'Penerima utama email',
                'b' => 'Salinan yang dikirim ke penerima lain tanpa sepengetahuan penerima utama',
                'c' => 'Lampiran dokumen',
                'd' => 'Salinan yang diketahui semua penerima',
                'e' => 'Pengiriman email yang terenkripsi',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Dalam komunikasi bisnis, pesan yang disampaikan oleh pengirim disebut...',
                'a' => 'Media',
                'b' => 'Feedback',
                'c' => 'Encoding',
                'd' => 'Pesan (message)',
                'e' => 'Noise',
                'jawaban' => 'd',
            ],
            [
                'pertanyaan' => 'Surat yang dibuat sebagai bukti bahwa seseorang telah bekerja di suatu instansi disebut...',
                'a' => 'Surat tugas',
                'b' => 'Surat keterangan',
                'c' => 'Surat kuasa',
                'd' => 'Surat rekomendasi',
                'e' => 'Surat pengangkatan',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Hambatan komunikasi yang berasal dari perbedaan bahasa atau istilah teknis yang tidak dipahami penerima disebut hambatan...',
                'a' => 'Fisik',
                'b' => 'Psikologis',
                'c' => 'Semantik',
                'd' => 'Sosiokultural',
                'e' => 'Organisasional',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Format surat yang pengetikannya dimulai dari margin kiri semua bagian surat disebut...',
                'a' => 'Full block style',
                'b' => 'Semi block style',
                'c' => 'Indented style',
                'd' => 'Hanging paragraph style',
                'e' => 'Simplified style',
                'jawaban' => 'a',
            ],

            // ── MANAJEMEN ARSIP & DOKUMEN (16-30) ──────────────────────────
            [
                'pertanyaan' => 'Sistem kearsipan yang mengelompokkan dokumen berdasarkan abjad nama disebut sistem...',
                'a' => 'Numerik',
                'b' => 'Alfabetis',
                'c' => 'Geografis',
                'd' => 'Kronologis',
                'e' => 'Subjek',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Proses pemindahan arsip dari tempat penyimpanan aktif ke tempat penyimpanan inaktif disebut...',
                'a' => 'Pemusnahan arsip',
                'b' => 'Pemeliharaan arsip',
                'c' => 'Pemindahan arsip',
                'd' => 'Penyerahan arsip',
                'e' => 'Penilaian arsip',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Arsip yang masih sering digunakan dan diperlukan dalam kegiatan sehari-hari organisasi disebut arsip...',
                'a' => 'Inaktif',
                'b' => 'Statis',
                'c' => 'Dinamis',
                'd' => 'Aktif',
                'e' => 'Vital',
                'jawaban' => 'd',
            ],
            [
                'pertanyaan' => 'Dokumen yang memiliki nilai guna permanen dan wajib diserahkan ke Arsip Nasional disebut...',
                'a' => 'Arsip aktif',
                'b' => 'Arsip inaktif',
                'c' => 'Arsip statis',
                'd' => 'Arsip dinamis',
                'e' => 'Arsip sementara',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Jadwal Retensi Arsip (JRA) digunakan untuk menentukan...',
                'a' => 'Cara pengindeksan dokumen',
                'b' => 'Jangka waktu penyimpanan dan nasib akhir arsip',
                'c' => 'Format penomoran surat',
                'd' => 'Metode digitalisasi dokumen',
                'e' => 'Prosedur pengiriman surat',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Filing cabinet dengan laci terbuka ke atas cocok untuk menyimpan dokumen dalam...',
                'a' => 'Map gantung (hanging folder)',
                'b' => 'Ordner besar',
                'c' => 'Box file',
                'd' => 'Snelhecter',
                'e' => 'Map biasa',
                'jawaban' => 'a',
            ],
            [
                'pertanyaan' => 'Proses mengalihkan arsip kertas ke bentuk digital (scan) disebut...',
                'a' => 'Digitalisasi arsip',
                'b' => 'Destruksi arsip',
                'c' => 'Akuisisi arsip',
                'd' => 'Autentikasi arsip',
                'e' => 'Indeksasi arsip',
                'jawaban' => 'a',
            ],
            [
                'pertanyaan' => 'Sistem kearsipan berdasarkan tempat/wilayah asal dokumen disebut sistem...',
                'a' => 'Numerik',
                'b' => 'Alfabetis',
                'c' => 'Geografis',
                'd' => 'Kronologis',
                'e' => 'Subjek/Masalah',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Tujuan utama pengelolaan kearsipan yang baik di suatu organisasi adalah...',
                'a' => 'Mengurangi jumlah pegawai',
                'b' => 'Mempercantik ruang kantor',
                'c' => 'Memudahkan penemuan kembali arsip saat dibutuhkan',
                'd' => 'Menghemat listrik',
                'e' => 'Menghindari audit',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Dokumen yang berisi daftar isi dari sekumpulan dokumen atau file disebut...',
                'a' => 'Daftar pertelaan arsip',
                'b' => 'Kartu indeks',
                'c' => 'Buku agenda',
                'd' => 'Lembar pengantar',
                'e' => 'Formulir peminjaman',
                'jawaban' => 'a',
            ],
            [
                'pertanyaan' => 'Buku yang digunakan untuk mencatat semua surat masuk dan surat keluar secara berurutan tanggalnya disebut...',
                'a' => 'Buku ekspedisi',
                'b' => 'Buku agenda',
                'c' => 'Lembar disposisi',
                'd' => 'Kartu kendali',
                'e' => 'Buku tamu',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Peraturan perundangan yang mengatur tentang kearsipan di Indonesia adalah...',
                'a' => 'UU No. 43 Tahun 2009',
                'b' => 'UU No. 11 Tahun 2008',
                'c' => 'UU No. 14 Tahun 2008',
                'd' => 'UU No. 25 Tahun 2009',
                'e' => 'UU No. 30 Tahun 2014',
                'jawaban' => 'a',
            ],
            [
                'pertanyaan' => 'Surat yang tidak penting dan tidak bernilai guna lagi sebaiknya...',
                'a' => 'Disimpan selamanya',
                'b' => 'Dipindahkan ke arsip inaktif',
                'c' => 'Dimusnahkan sesuai prosedur',
                'd' => 'Diberikan kepada siapa saja',
                'e' => 'Ditaruh di sembarang tempat',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Sistem penomoran pada kearsipan yang menggunakan angka sebagai kode dokumen disebut sistem...',
                'a' => 'Alfanumerik',
                'b' => 'Numerik',
                'c' => 'Kronologis',
                'd' => 'Subjek',
                'e' => 'Geografis',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Lembar yang digunakan untuk mencatat instruksi atau perintah dari pimpinan mengenai penanganan surat disebut...',
                'a' => 'Lembar ekspedisi',
                'b' => 'Lembar disposisi',
                'c' => 'Kartu indeks',
                'd' => 'Buku agenda',
                'e' => 'Kartu kendali',
                'jawaban' => 'b',
            ],

            // ── MANAJEMEN WAKTU & PENJADWALAN (31-45) ──────────────────────
            [
                'pertanyaan' => 'Prioritas tugas dalam manajemen waktu yang paling efektif menurut Matriks Eisenhower adalah...',
                'a' => 'Penting dan mendesak',
                'b' => 'Tidak penting dan mendesak',
                'c' => 'Penting dan tidak mendesak',
                'd' => 'Tidak penting dan tidak mendesak',
                'e' => 'Semua tugas sama penting',
                'jawaban' => 'a',
            ],
            [
                'pertanyaan' => 'Aplikasi yang umum digunakan untuk mengelola kalender dan jadwal pertemuan pimpinan secara digital adalah...',
                'a' => 'Microsoft Word',
                'b' => 'Microsoft Excel',
                'c' => 'Google Calendar / Microsoft Outlook',
                'd' => 'Adobe Photoshop',
                'e' => 'Notepad',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Sekretaris yang baik dalam mengatur jadwal pimpinan harus memperhatikan...',
                'a' => 'Kepentingan pribadi sekretaris',
                'b' => 'Prioritas dan keterkaitan antar jadwal pimpinan',
                'c' => 'Hanya jadwal rapat saja',
                'd' => 'Selera pimpinan dalam hal waktu makan siang',
                'e' => 'Jadwal sekretaris lain',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Konfirmasi ulang janji temu (reminder) kepada pimpinan sebaiknya dilakukan...',
                'a' => 'Seminggu sebelum pertemuan',
                'b' => 'Sehari sebelum dan pada pagi hari pertemuan',
                'c' => 'Hanya jika pimpinan meminta',
                'd' => 'Saat pertemuan sudah dimulai',
                'e' => 'Tidak perlu dilakukan',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Pengaturan perjalanan dinas pimpinan yang perlu dipersiapkan sekretaris meliputi, KECUALI...',
                'a' => 'Pemesanan tiket transportasi',
                'b' => 'Pemesanan akomodasi/hotel',
                'c' => 'Menyiapkan dokumen yang diperlukan',
                'd' => 'Mengurus urusan keluarga pimpinan',
                'e' => 'Membuat itinerary perjalanan',
                'jawaban' => 'd',
            ],
            [
                'pertanyaan' => 'Alat bantu manajemen proyek yang menampilkan jadwal tugas dalam bentuk batang horizontal disebut...',
                'a' => 'Flow chart',
                'b' => 'Gantt chart',
                'c' => 'Mind map',
                'd' => 'PERT chart',
                'e' => 'Pie chart',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'To-do list yang efektif sebaiknya disusun berdasarkan...',
                'a' => 'Urutan abjad',
                'b' => 'Urutan yang paling disukai',
                'c' => 'Prioritas dan tenggat waktu',
                'd' => 'Panjang pendeknya tugas',
                'e' => 'Siapa yang meminta',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Dalam persiapan rapat, undangan rapat sebaiknya dikirim...',
                'a' => 'Saat rapat sudah dimulai',
                'b' => 'Sehari sebelum rapat',
                'c' => 'Setidaknya beberapa hari sebelum rapat agar peserta dapat mempersiapkan diri',
                'd' => 'Sebulan sebelum rapat',
                'e' => 'Tidak perlu undangan untuk rapat informal',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Dokumen yang berisi rencana topik yang akan dibahas dalam suatu rapat disebut...',
                'a' => 'Notula',
                'b' => 'Agenda rapat',
                'c' => 'Risalah rapat',
                'd' => 'Laporan rapat',
                'e' => 'Daftar hadir',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Perjalanan dinas yang melibatkan penerbangan internasional memerlukan dokumen wajib berupa...',
                'a' => 'KTP saja',
                'b' => 'SIM dan KTP',
                'c' => 'Paspor yang masih berlaku',
                'd' => 'Kartu kredit perusahaan',
                'e' => 'Surat tugas saja',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Teknik manajemen waktu "Pomodoro" menganjurkan bekerja fokus selama berapa menit sebelum istirahat singkat?',
                'a' => '10 menit',
                'b' => '25 menit',
                'c' => '45 menit',
                'd' => '60 menit',
                'e' => '90 menit',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Saat pimpinan memiliki dua jadwal yang bertabrakan, langkah pertama yang harus dilakukan sekretaris adalah...',
                'a' => 'Membatalkan salah satu jadwal tanpa konfirmasi',
                'b' => 'Menginformasikan konflik jadwal tersebut kepada pimpinan untuk mendapat keputusan',
                'c' => 'Menjawab sendiri sesuai pertimbangan pribadi',
                'd' => 'Membiarkan saja dan menunggu',
                'e' => 'Menghubungi pihak luar tanpa izin pimpinan',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Travel document check-list untuk perjalanan dinas luar negeri meliputi, KECUALI...',
                'a' => 'Paspor',
                'b' => 'Visa (jika diperlukan)',
                'c' => 'Tiket pesawat',
                'd' => 'Kartu BPJS Kesehatan',
                'e' => 'Surat tugas',
                'jawaban' => 'd',
            ],
            [
                'pertanyaan' => 'Rapat yang diadakan untuk membahas laporan kinerja tahunan perusahaan disebut rapat...',
                'a' => 'Rapat koordinasi',
                'b' => 'Rapat kerja',
                'c' => 'Rapat umum pemegang saham (RUPS)',
                'd' => 'Rapat insidental',
                'e' => 'Rapat informal',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Pengaturan tempat duduk dalam rapat yang menempatkan pimpinan di ujung meja dengan peserta di sisi kiri-kanan disebut...',
                'a' => 'Classroom style',
                'b' => 'U-shape style',
                'c' => 'Boardroom style',
                'd' => 'Theater style',
                'e' => 'Banquet style',
                'jawaban' => 'c',
            ],

            // ── TEKNOLOGI KANTOR & PERALATAN (46-60) ───────────────────────
            [
                'pertanyaan' => 'Perangkat lunak pengolah kata (word processor) yang paling umum digunakan di perkantoran adalah...',
                'a' => 'Microsoft Excel',
                'b' => 'Microsoft PowerPoint',
                'c' => 'Microsoft Word',
                'd' => 'Microsoft Access',
                'e' => 'Microsoft Outlook',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Fungsi VLOOKUP di Microsoft Excel digunakan untuk...',
                'a' => 'Membuat grafik',
                'b' => 'Mencari nilai dalam kolom pertama suatu tabel dan mengambil nilai dari kolom lain',
                'c' => 'Menghitung rata-rata',
                'd' => 'Menyortir data',
                'e' => 'Membuat pivot table',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Shortcut keyboard untuk menyimpan dokumen di Microsoft Office adalah...',
                'a' => 'Ctrl + P',
                'b' => 'Ctrl + Z',
                'c' => 'Ctrl + S',
                'd' => 'Ctrl + C',
                'e' => 'Ctrl + V',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Format file yang aman untuk berbagi dokumen agar tidak mudah diubah pihak lain adalah...',
                'a' => '.docx',
                'b' => '.xlsx',
                'c' => '.pdf',
                'd' => '.txt',
                'e' => '.pptx',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Alat kantor yang digunakan untuk menggandakan dokumen dalam jumlah banyak dengan cepat adalah...',
                'a' => 'Scanner',
                'b' => 'Printer inkjet',
                'c' => 'Mesin fotokopi/Risograph',
                'd' => 'Faksimile',
                'e' => 'Proyektor',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Cloud storage seperti Google Drive digunakan di perkantoran untuk...',
                'a' => 'Mengedit video',
                'b' => 'Menyimpan dan berbagi dokumen secara online',
                'c' => 'Membuat presentasi hanya offline',
                'd' => 'Menggantikan seluruh server lokal',
                'e' => 'Mengamankan jaringan Wi-Fi',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Kegiatan membuat cadangan data penting secara berkala disebut...',
                'a' => 'Formatting',
                'b' => 'Defragmenting',
                'c' => 'Backup',
                'd' => 'Partitioning',
                'e' => 'Upgrading',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Tanda tangan digital (digital signature) dalam dokumen elektronik berfungsi untuk...',
                'a' => 'Memperindah tampilan dokumen',
                'b' => 'Membuktikan keaslian dan integritas dokumen',
                'c' => 'Mempercepat pengiriman email',
                'd' => 'Mengkompresi ukuran file',
                'e' => 'Mengubah format dokumen',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Jaringan komputer yang menghubungkan komputer dalam satu gedung atau area terbatas disebut...',
                'a' => 'WAN (Wide Area Network)',
                'b' => 'MAN (Metropolitan Area Network)',
                'c' => 'LAN (Local Area Network)',
                'd' => 'VPN (Virtual Private Network)',
                'e' => 'Internet',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Dalam presentasi menggunakan PowerPoint, tombol F5 digunakan untuk...',
                'a' => 'Menyimpan file',
                'b' => 'Membuka file baru',
                'c' => 'Memulai slideshow dari awal',
                'd' => 'Menutup program',
                'e' => 'Mencetak presentasi',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Mesin yang dapat mengirim dan menerima dokumen melalui jalur telepon disebut...',
                'a' => 'Printer',
                'b' => 'Scanner',
                'c' => 'Faksimile (Fax)',
                'd' => 'Fotokopi',
                'e' => 'Plotter',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Sistem manajemen dokumen elektronik (EDMS/DMS) di kantor digunakan untuk...',
                'a' => 'Mengontrol akses internet karyawan',
                'b' => 'Menyimpan, mengelola, dan melacak dokumen elektronik secara terpusat',
                'c' => 'Menghitung gaji karyawan',
                'd' => 'Membuat desain grafis',
                'e' => 'Merekam percakapan telepon',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Saat menggunakan printer, istilah "DPI" mengacu pada...',
                'a' => 'Kecepatan cetak per halaman',
                'b' => 'Resolusi cetak (titik per inci)',
                'c' => 'Kapasitas tinta',
                'd' => 'Ukuran kertas yang didukung',
                'e' => 'Koneksi jaringan printer',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Konferensi video (video conference) di kantor membutuhkan perangkat, KECUALI...',
                'a' => 'Kamera webcam',
                'b' => 'Mikrofon dan speaker',
                'c' => 'Koneksi internet yang stabil',
                'd' => 'Mesin faksimile',
                'e' => 'Perangkat lunak konferensi (Zoom, Teams, dll)',
                'jawaban' => 'd',
            ],
            [
                'pertanyaan' => 'Fungsi pivot table di Microsoft Excel adalah...',
                'a' => 'Membuat grafik lingkaran',
                'b' => 'Merangkum dan menganalisis data dalam jumlah besar secara interaktif',
                'c' => 'Membuat form input data',
                'd' => 'Menghapus data duplikat',
                'e' => 'Mencetak spreadsheet',
                'jawaban' => 'b',
            ],

            // ── KEPRIBADIAN & ETIKA PROFESI (61-75) ────────────────────────
            [
                'pertanyaan' => 'Sikap menjaga kerahasiaan informasi perusahaan yang tidak boleh disebarkan kepada pihak luar disebut...',
                'a' => 'Loyalitas',
                'b' => 'Kejujuran',
                'c' => 'Kerahasiaan (confidentiality)',
                'd' => 'Disiplin',
                'e' => 'Tanggung jawab',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Penampilan profesional seorang sekretaris/tenaga administrasi kantor meliputi...',
                'a' => 'Berpakaian sesuai tren fashion terkini',
                'b' => 'Berpakaian rapi, sopan, dan sesuai budaya kerja perusahaan',
                'c' => 'Mengenakan aksesoris berlebihan',
                'd' => 'Berpakaian sebebas mungkin',
                'e' => 'Tidak perlu memperhatikan penampilan selama bekerja dengan baik',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Etika bertamu ke kantor yang baik adalah...',
                'a' => 'Langsung masuk ruangan pimpinan tanpa mengetuk',
                'b' => 'Membuat janji terlebih dahulu dan melapor kepada resepsionis',
                'c' => 'Datang tanpa pemberitahuan untuk kejutan',
                'd' => 'Menunggu di luar gedung tanpa melapor',
                'e' => 'Menelepon staf level rendah',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Berikut yang merupakan cerminan sikap profesional dalam bekerja, KECUALI...',
                'a' => 'Datang tepat waktu',
                'b' => 'Menyelesaikan tugas sesuai tenggat waktu',
                'c' => 'Bergosip tentang rekan kerja',
                'd' => 'Menjaga kerahasiaan perusahaan',
                'e' => 'Bersikap ramah kepada tamu',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Dalam etika menerima tamu penting, hal yang pertama dilakukan resepsionis adalah...',
                'a' => 'Mempersilahkan tamu langsung ke ruangan pimpinan',
                'b' => 'Menyambut dengan senyum, menanyakan identitas dan keperluan tamu',
                'c' => 'Meminta tamu mengisi buku tamu tanpa disapa',
                'd' => 'Menelepon pimpinan tanpa menyapa tamu',
                'e' => 'Meminta tamu menunggu tanpa kejelasan',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Konflik kepentingan (conflict of interest) di tempat kerja terjadi ketika...',
                'a' => 'Karyawan memiliki dua pekerjaan',
                'b' => 'Kepentingan pribadi karyawan berpotensi mempengaruhi pengambilan keputusan profesionalnya',
                'c' => 'Karyawan tidak sependapat dengan atasan',
                'd' => 'Ada perbedaan budaya antar karyawan',
                'e' => 'Karyawan merasa gajinya kurang',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Whistleblowing dalam konteks etika bisnis berarti...',
                'a' => 'Mengadukan kesalahan perusahaan kepada pihak berwenang',
                'b' => 'Bersiul di tempat kerja',
                'c' => 'Memberikan bonus kepada karyawan berprestasi',
                'd' => 'Meniup peluit sebagai tanda bahaya',
                'e' => 'Memberitahu rekan kerja tentang gosip',
                'jawaban' => 'a',
            ],
            [
                'pertanyaan' => 'Grooming standar untuk seorang sekretaris profesional wanita di lingkungan kerja formal meliputi...',
                'a' => 'Riasan tebal dan parfum menyengat',
                'b' => 'Riasan natural, pakaian bersih rapi, rambut tertata',
                'c' => 'Tidak perlu bersolek sama sekali',
                'd' => 'Menggunakan perhiasan sebanyak mungkin',
                'e' => 'Berpakaian casual setiap hari',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Kode etik profesi dibuat untuk...',
                'a' => 'Membatasi kreativitas karyawan',
                'b' => 'Menjadi pedoman perilaku dan standar moral dalam menjalankan profesi',
                'c' => 'Meningkatkan gaji karyawan',
                'd' => 'Menghindari pembayaran pajak',
                'e' => 'Mempersulit perizinan usaha',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Dalam situasi menerima hadiah dari mitra bisnis, sikap profesional yang tepat adalah...',
                'a' => 'Menerima semua hadiah tanpa lapor',
                'b' => 'Menolak atau melaporkan kepada atasan sesuai kebijakan perusahaan',
                'c' => 'Meminta hadiah lebih besar',
                'd' => 'Menerima hanya jika tidak ada yang tahu',
                'e' => 'Membagikan hadiah kepada rekan kerja',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Kemampuan mengelola emosi di tempat kerja agar tetap produktif dan profesional disebut...',
                'a' => 'IQ (Intelligence Quotient)',
                'b' => 'SQ (Spiritual Quotient)',
                'c' => 'EQ (Emotional Quotient)',
                'd' => 'AQ (Adversity Quotient)',
                'e' => 'CQ (Creative Quotient)',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Tata cara berpakaian formal dalam dunia kerja (dress code) diterapkan untuk...',
                'a' => 'Membedakan jabatan karyawan',
                'b' => 'Menciptakan kesan profesional dan seragam dalam organisasi',
                'c' => 'Menghemat biaya pakaian karyawan',
                'd' => 'Menghindari kecemburuan sosial',
                'e' => 'Memudahkan identifikasi karyawan oleh satpam',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Prinsip "SMART" dalam menetapkan target kerja berarti...',
                'a' => 'Simple, Meaningful, Achievable, Realistic, Timely',
                'b' => 'Specific, Measurable, Achievable, Relevant, Time-bound',
                'c' => 'Strategic, Manageable, Attainable, Reasonable, Trackable',
                'd' => 'Specific, Motivating, Actionable, Realistic, Timely',
                'e' => 'Simple, Measurable, Achievable, Reachable, Time-based',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Contoh perilaku yang mencerminkan integritas di tempat kerja adalah...',
                'a' => 'Menggunakan fasilitas kantor untuk kepentingan pribadi',
                'b' => 'Melaporkan temuan yang kurang menguntungkan secara jujur',
                'c' => 'Melebih-lebihkan laporan kinerja',
                'd' => 'Menyalahkan rekan kerja atas kesalahan sendiri',
                'e' => 'Mangkir kerja tanpa keterangan',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Dalam etiket bisnis, pertukaran kartu nama (business card) yang benar adalah...',
                'a' => 'Melempar kartu nama ke arah lawan bicara',
                'b' => 'Memberikan dan menerima kartu nama dengan dua tangan sambil membacanya sejenak',
                'c' => 'Langsung memasukkan kartu nama ke saku tanpa melihat',
                'd' => 'Menolak kartu nama jika tidak diperlukan',
                'e' => 'Memberikan kartu nama sambil menggunakan tangan kiri',
                'jawaban' => 'b',
            ],

            // ── KEUANGAN & ADMINISTRASI UMUM (76-90) ───────────────────────
            [
                'pertanyaan' => 'Dokumen yang berisi permintaan pengeluaran uang dari kas perusahaan untuk kebutuhan operasional disebut...',
                'a' => 'Faktur',
                'b' => 'Voucher kas',
                'c' => 'Kwitansi',
                'd' => 'Nota kredit',
                'e' => 'Slip gaji',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Petty cash (kas kecil) di kantor digunakan untuk...',
                'a' => 'Pembayaran gaji karyawan',
                'b' => 'Pengeluaran rutin kecil yang tidak memerlukan cek atau transfer bank',
                'c' => 'Investasi perusahaan jangka panjang',
                'd' => 'Membayar hutang perusahaan',
                'e' => 'Pembelian aset tetap',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Laporan yang merangkum pendapatan dan pengeluaran perusahaan dalam periode tertentu disebut...',
                'a' => 'Neraca',
                'b' => 'Laporan arus kas',
                'c' => 'Laporan laba rugi',
                'd' => 'Laporan perubahan modal',
                'e' => 'Laporan posisi keuangan',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Prosedur pengadaan barang/jasa di instansi pemerintah mengacu pada peraturan...',
                'a' => 'Perpres No. 16 Tahun 2018 tentang Pengadaan Barang/Jasa Pemerintah',
                'b' => 'UU No. 43 Tahun 2009',
                'c' => 'UU No. 11 Tahun 2008',
                'd' => 'Perpres No. 54 Tahun 2010 saja',
                'e' => 'UU Ketenagakerjaan No. 13 Tahun 2003',
                'jawaban' => 'a',
            ],
            [
                'pertanyaan' => 'Formulir yang digunakan untuk mencatat barang yang masuk dan keluar dari gudang kantor disebut...',
                'a' => 'Purchase order',
                'b' => 'Kartu stok/kartu gudang',
                'c' => 'Invoice',
                'd' => 'Delivery order',
                'e' => 'Bill of lading',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Reimbursement dalam konteks administrasi keuangan kantor berarti...',
                'a' => 'Pemberian pinjaman kepada karyawan',
                'b' => 'Penggantian biaya yang telah dikeluarkan karyawan untuk keperluan dinas',
                'c' => 'Pemotongan gaji karyawan',
                'd' => 'Bonus akhir tahun',
                'e' => 'Pembayaran lembur',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'SOP (Standard Operating Procedure) di kantor berfungsi untuk...',
                'a' => 'Mempersulit pekerjaan karyawan',
                'b' => 'Memberikan panduan langkah-langkah standar dalam melaksanakan suatu pekerjaan',
                'c' => 'Menggantikan peran atasan',
                'd' => 'Hanya berlaku untuk pekerjaan teknis',
                'e' => 'Mengurangi produktivitas',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Tata ruang kantor yang menempatkan semua karyawan dalam satu ruangan besar tanpa sekat permanen disebut...',
                'a' => 'Private office layout',
                'b' => 'Cubicle layout',
                'c' => 'Open plan office layout',
                'd' => 'Combination layout',
                'e' => 'Landscape office',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Ergonomi dalam desain tempat kerja bertujuan untuk...',
                'a' => 'Memperindah tampilan kantor',
                'b' => 'Menyesuaikan lingkungan kerja dengan kebutuhan fisik dan psikologis karyawan',
                'c' => 'Mengurangi biaya furnitur',
                'd' => 'Menambah kapasitas ruang',
                'e' => 'Mengikuti tren desain interior',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Program K3 (Keselamatan dan Kesehatan Kerja) di kantor diatur dalam...',
                'a' => 'UU No. 1 Tahun 1970',
                'b' => 'UU No. 13 Tahun 2003',
                'c' => 'UU No. 43 Tahun 2009',
                'd' => 'UU No. 8 Tahun 1974',
                'e' => 'UU No. 25 Tahun 2009',
                'jawaban' => 'a',
            ],
            [
                'pertanyaan' => 'Penilaian kinerja karyawan secara 360 derajat artinya penilaian dilakukan oleh...',
                'a' => 'Hanya atasan langsung',
                'b' => 'Hanya rekan kerja',
                'c' => 'Atasan, rekan kerja, bawahan, dan diri sendiri',
                'd' => 'Tim HRD saja',
                'e' => 'Pihak eksternal saja',
                'jawaban' => 'c',
            ],
            [
                'pertanyaan' => 'Asuransi BPJS Ketenagakerjaan memberikan perlindungan kepada karyawan berupa, KECUALI...',
                'a' => 'Jaminan kecelakaan kerja',
                'b' => 'Jaminan hari tua',
                'c' => 'Jaminan kematian',
                'd' => 'Jaminan pemilikan rumah',
                'e' => 'Jaminan pensiun',
                'jawaban' => 'd',
            ],
            [
                'pertanyaan' => 'Dokumen yang berisi rincian barang/jasa yang dikirim beserta harganya, dikirim oleh penjual kepada pembeli, disebut...',
                'a' => 'Purchase order',
                'b' => 'Invoice/Faktur',
                'c' => 'Delivery note',
                'd' => 'Credit note',
                'e' => 'Receipt',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Sistem penomoran surat keluar yang baik harus mencantumkan...',
                'a' => 'Hanya tanggal surat',
                'b' => 'Nomor urut, kode unit, kode jenis surat, dan tahun',
                'c' => 'Nama pengirim saja',
                'd' => 'Nama penerima dan topik',
                'e' => 'Nomor telepon pengirim',
                'jawaban' => 'b',
            ],
            [
                'pertanyaan' => 'Kegiatan "benchmarking" dalam manajemen perkantoran berarti...',
                'a' => 'Menetapkan target keuangan',
                'b' => 'Membandingkan proses/kinerja dengan standar terbaik untuk perbaikan',
                'c' => 'Mengukur tinggi meja kerja',
                'd' => 'Menilai kepuasan pelanggan',
                'e' => 'Membuat laporan tahunan',
                'jawaban' => 'b',
            ],
        ];
    }
}